# Generated by Django 5.1.5 on 2025-05-09 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "myapp",
            "0012_rename_glucose_level_bloodanalysis_erythrocytes_level_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="BloodCellAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="blood_cell_images/")),
                ("prediction", models.CharField(max_length=100)),
                ("confidence", models.FloatField()),
                ("saliency_map", models.ImageField(upload_to="saliency_maps/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
