# Generated by Django 5.1.5 on 2025-05-15 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0014_bloodcellanalysis_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bloodanalysis",
            name="analysis_file",
        ),
        migrations.AddField(
            model_name="bloodanalysis",
            name="amylase_level",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bloodanalysis",
            name="basophils_level",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bloodanalysis",
            name="c_reactive_protein_level",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bloodanalysis",
            name="creatinine_level",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bloodanalysis",
            name="potassium_level",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
