# Generated by Django 5.1.5 on 2025-05-15 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0015_remove_bloodanalysis_analysis_file_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bloodanalysis",
            name="analysis_file",
            field=models.FileField(null=True, upload_to="uploads/analysis/"),
        ),
    ]
